language: clojure
before_deploy: lein uberjar
deploy:
  provider: s3
  region: us-west-2
  access_key_id: AKIAI4JARJT7CP4WBDTQ
  secret_access_key:
    secure: hsvKprB8FzgJZbxhNvJ2YllV7E0VU2HQStWsuckvwpHOZiYqovTz3zOZEAu287Xu3YtbMxn6lz4gN7ZaO53cN/4aivdJv9aQWXA0ouHCWLshWsm87msdvxpWdV/hUlVwCrMMxbObIw6tpeXyTomqaFxqx/u/Pk/Aqvad4nk82GPmGblr/kPhNDAHXlTsUvOBvl7PLAQy2K1vfjg68tRsuaTcuICEn/5Jk0rwggYzotnGoYYVEEFYkTDNM2AsPRv4nLCCSUDYjXnclDnFVjuUZCPlcGO4T/UJ+Cjcccukrdi4LpVe/y5eNyyAcFLf2qNDG1mTg5zEjhbQZezopDYd/QY4to/godfZu4tQMtJ+QsnnFEjIQ+E0Kgn9eBkZ3MJUiw1/xZQsqBqbw7dyOsW/FR34s/2rsDrA87Up5coT73fgudwD6E7gpb8W7crAK8RlQBsbJQm+3v9R5mHXHmMVotmYxS5o3uv0Vko+aBBUb07yUypT0Obwanw0TkxALfdFZs9S8NY/P/L6SYKIqAcZ0t1Ej8a2oEdaSl3J+3l1P0XseUK8pVFqOeD+babPhrl4/CVoQbH2/6XLhh8xZeUrkS1QqlNjzdvmI6fuqh2KqbU6+hmzvHXLHW3nBsa1saQtdew9qJg4oRnsSDjqK5Avl6p7fYHV7Wxvo3fIqLVLCEI=
  bucket: steam-score
  file: target/uberjar/steam-score-lambda.jar
  acl: private
  on:
    repo: nicknovitski/steam-score-lambda
    branch: master
